#!/bin/bash

#HELP	<RID/OID> - checks if pckg has been delivered and opens slots of the last delivery batch one after another

proceed()
{
	read -p "Proceed with the next slot?(y/n)" YN
		
	case "$YN" in
		Y|y) echo "Moving to the next slot";;
		N|n) echo "Ending the script"; exit;;
		*) echo "Invalid option..."; proceed;;
	esac
}

ID=$(grep -w $1 /usr/local/dpcs/DeliveryPointClientService.log | grep "CUSTOMER_PICKUP" | grep -v "ItemConsolidated" | tail -n 1 | sed 's/ /\n/g' | grep "reservationId=" | tr -d "[reservationId=,"; zgrep -w $1 `ls -r /tmp/kiosklogpusher/backup/DeliveryPointClientService* | head -n 2` | grep "CUSTOMER_PICKUP" | grep -v "ItemConsolidated" | tail -n 1 | sed 's/ /\n/g' | grep "reservationId=" | tr -d "[reservationId=,")

if [ -z "$ID" ]
then
	echo "Package $1 is invalid or not ordered for this locker or it might has been delivered more than 120 minutes ago."
else
	LID=$(grep -A 100 -i "Authenticating carrier credentials:"  /usr/local/dpcs/DeliveryPointClientService.log | grep "LID(.*Opening" | cut -d " " -f 10 | tr -d "LID()"; zgrep -A 100 -i "Authenticating carrier credentials:" `ls -r /tmp/kiosklogpusher/backup/DeliveryPointClientService* | head -n 8` | grep "LID(.*Opening" | cut -d " " -f 10 | tr -d "LID()")
	LIDS+=("$LID")
fi

cd /usr/local/dpcs

for SLOT in ${LIDS[*]}

do
	echo "Opening slot number $SLOT"

	sudo ./lockerController.sh -o -d $SLOT
		
	while sudo ./lockerController.sh -s -d $SLOT | grep "Open: true"
	do
		echo "Close slot $SLOT, please"
	done
		
	proceed
done

echo "Ending the script"
