#!/bin/bash

#HELP   Latest DPCS error logs (tail).

LOG_SIZE=${LOG_SIZE:-30}

OUTPUT=$(mktemp -u)

grep -i "ERROR" /usr/local/dpcs/DeliveryPointClientService.log \
	| tail -n ${LOG_SIZE} >> ${OUTPUT}

if (( $(wc -l ${OUTPUT} | awk '{print $1}') > 0 )); then
	cat ${OUTPUT}
else
	echo "- Nothing found."
fi
