#!/bin/sh

URL_INSTALLER="https://opstechit-fr.s3.amazonaws.com/klang/klanginst"
URL_PACKED="https://opstechit-fr.s3.amazonaws.com/klang/install.zip"

echo "- Downloading Klang!..."
cd $(mktemp -d --suffix=".klang")
mkdir -p ${HOME}/bin
wget -qP . ${URL_PACKED}
unzip -oq ./install.zip -d ${HOME}/bin
chmod a+x ${HOME}/bin/*

sed -i "s%^.*klang.*%%g" ${HOME}/.bashrc

echo "wget -qO - \"${URL_INSTALLER}\" | \${SHELL}" >> ${HOME}/.bashrc

echo "- Klang! successfully installed and it is ready to use!"
echo "- Type klang to see the list of commands" | grep --color "klang\|"
