#!/bin/bash

#HELP	UPS charge and apcupsd report.

print_formatted() { echo "# ${@}" | grep --color ".*"; }

LOG_SIZE=${LOG_SIZE:-30}

OUTPUT=$(mktemp)
apcaccess >> ${OUTPUT}

sudo service apcupsd restart
echo

KEY="UPSBatteryPercentMetric"
print_formatted ${KEY}
grep ${KEY} /usr/local/kioskmonitoringtools/kioskwatcher.log* \
	| awk -F ',' '{print $7":"$6}' \
	| awk -F ':' '{print strftime("%F %H:%M:%S",$2)"\tBCHARGE: "$4"%"}' \
	| sort | tail -n ${LOG_SIZE}
echo

print_formatted "apcupsd.events"
grep -ahi  "battery\|failure\|reached\|running\|shutdown\|startup" /var/log/apcupsd.events* \
	| sort | tail -n ${LOG_SIZE}
echo

print_formatted "apcaccess"
cat ${OUTPUT} | grep --color "STATUS\|BCHARGE\|"
TIMELEFT=$(cat ${OUTPUT} | grep "TIMELEFT" | grep -o '[0-9.]*')
if (( ${TIMELEFT%.*} > 300 )); then
	echo
	print_formatted "*** UPS ALARM ***"
	echo "- Please ask the field engineer to connect the power strip to the UPS port labeled \"MASTER\". It is currently connected to the \"Controlled by MASTER\"."
	sleep $(( LOG_SIZE / 7 + 1 ))
fi
