#!/bin/bash

#HELP   General health check.

format_msg() { echo -e "\n\n\n\e[1;96m┌───────────#\t${@}\e[0m"; }

export LOG_SIZE=${LOG_SIZE:-15}

format_msg "OS version, image date:"
os

format_msg "Last reboot, uptime, hwclock fix:"
last reboot | tac | tail -n ${LOG_SIZE}
echo
uptime -p
echo
echo "pkill -9 ntp; ntpdate 0.us.pool.ntp.org; /etc/init.d/S90SyncKioskTime restart; service ntpd restart; hwclock" | sudo -s

format_msg "USB connections:"
lsusb | grep -i -v "Linux"

format_msg "UPS logs, status, fix:"
ups

format_msg "Screen, scanner:"
screen
echo
echo
scanner

format_msg "SVB, PCBs:"
boards

format_msg "Internet connection:"
netlog

format_msg "Latest DPCS errors:"
error

format_msg "Latest AZBox logs:"
azbox

# format_msg "USB/Scanner detection logs:"
# usbissue
