#!/usr/bin/env python
# -*- coding: utf-8 -*-

#HELP	Displays this help message.

from os import listdir, path
from sys import argv

PWD = path.dirname(path.realpath(__file__))

def my_grep(key, source, strip = False):

	for line in source if isinstance(source, file) else source.split("\n"):
		if key in line:
			return line if not strip else line.strip(key).strip()

def format_text(text, color = None, bold = False):

	colors = {
		"silver": 2,
		"red": 31,
		"green": 32,
		"yellow": 33,
		"blue": 34,
		"magenta": 35,
		"cyan": 36,
		"gray": 90
	}

	if not color:
		return "\033[%dm%s\033[0m" % (bold, text)

	else:
		return "\033[%d;%dm%s\033[0m" % (bold, colors[color.lower()], text)

def get_help(files):

	result = dict()
	key = "#HELP"

	for command in files:
		with open(path.join(PWD, command), 'r') as filename:
			result[command] = my_grep(key, filename, strip = True)

	return result

if __name__ == "__main__":

	policy = "https://policy.amazon.com/procedure/62872"
	authors = ["zbeyer", "jnoguei", "gezapork"]

	print "# %s command list:" % format_text("OpsTechIT - Klang! - Kiosk Language", "yellow", bold = True)
	print format_text("├ %s" % format_text(policy, "blue"), "gray")
	print format_text("└ authors: %s.\n" % ", ".join([a + '@' for a in authors]), "gray")

	content = get_help(listdir(PWD) if not len(argv[1:]) else argv[1:])

	for key in sorted(content):
		if content[key]:
			print "* %s:\n\t%s" % (format_text(key, bold = True), format_text(content[key].replace("\\n", "\n\t"), "silver"))
