#!/bin/bash

#HELP	Resume of the latest "traceroute" logs.

print_colored() {

	local IFS=$'\n'

	for LINE in $(cat); do
		local GREEN=$(grep -io "online" <<< ${LINE})
		local RED=$(grep -io "offline" <<< ${LINE})
		
		if [[ ${GREEN} ]]; then
			LINE="\e[92m${LINE}\e[0m"
		fi

		if [[ ${RED} ]]; then
			LINE="\e[91m${LINE}\e[0m"
		fi

		echo -e ${LINE}
	done
}

########## MAIN ##########

LOG_SIZE=${LOG_SIZE:-50}
DAYS_AGO=${DAYS_AGO:-$(( LOG_SIZE / 7 + 1 ))}

cd $(mktemp -d --suffix=".klang-$(basename ${0})")

KEY="#UTC_Time:"

zgrep -ah ${KEY} \
	$(find {/tmp/kiosklogpusher/backup,/usr/local/kiosk*/monlogs}/traceroute.dat* \
	-mtime -${DAYS_AGO}) \
	&> raw.log

grep "^${KEY}" raw.log | awk '{print $2"...............OFFLINE"}' > offline.log
grep -v "^${KEY}" raw.log | grep -o "${KEY}.*" | awk '{print $2"...............ONLINE"}' > online.log

for LINE in $(sort -u *line.log); do

	if [[ ${PREVIOUS} != *$(grep -oE "[^.]+$" <<< ${LINE})* ]]; then
		echo ${LINE} >> processed.log
	fi

	PREVIOUS=${LINE}
done

tail -n ${LOG_SIZE} processed.log > result.log

echo -e "# Showing the last $(wc -l < result.log) events from the past ${DAYS_AGO} days:"
cat result.log | print_colored

echo -e "\e[1m$(date '+%F-%T' | tr ':' '-')...............NOW\e[0m"
