#!/bin/bash

#HELP	Repeated Null Locker Controller Responses

print_formatted() { echo "# ${@}" | grep --color ".*"; }

########## MAIN ##########

OUTPUT=$(mktemp)

print_formatted "Checking DPCS logs for non-responding boards:"

{ zgrep -h "Empty Response for IP" \
	$(find {/tmp/kiosklogpusher/backup,/usr/local/dpcs}/DeliveryPointClientService.log*) \
	| sed -e "s/\..*PST.*Command/ -/" -e "s/\..*PDT.*Command/ -/" \
	| tr -d '")' | sort >> ${OUTPUT}; } 2> /dev/null

(( $(wc -l < ${OUTPUT}) )) \
	&& cat ${OUTPUT} \
	|| echo "- Nothing found."
echo

print_formatted "Current date:"; date +"%F %T"
echo

print_formatted "Ping results:"
boards
