#!/bin/bash

#HELP	Downloads and launches the RHEL environment.

RHEL_URL=${RHEL_URL:-"https://s3.amazonaws.com/azbox/AmazonTest_rhel7.v1.19"}

BIN=$(find /tmp/*klang* -name rhel 2> /dev/null | tail -n 1)

if [ ! ${BIN} ]; then
	cd $(mktemp -d --suffix=".klang-$(basename ${0})")
	wget -O ./rhel ${RHEL_URL}
else
	cd $(dirname ${BIN})
fi

FIRMWARE_URL=${FIRMWARE_URL:-"https://s3.amazonaws.com/azbox/v2.08.bin"}

if [ ! -f $(basename ${FIRMWARE_URL}) ]; then
	wget -P . ${FIRMWARE_URL}
fi

echo "
service S99DPCS stop
service iptables stop
chmod a+x ./rhel
" | sudo -s
echo

sudo ./rhel eth1
echo

echo "
chown -R ${USER} .
service S99DPCS restart
service iptables restart
" | sudo -s
echo

tail ./*$(date +%F).txt
