#!/bin/bash

#HELP	downloads and launches the RHEL environment.

RHEL_URL="https://s3.amazonaws.com/azbox/AmazonTest_rhel7.v1.19"

BIN=$(find /tmp/*klang* -name rhel 2> /dev/null | tail -n 1)

if [ ! ${BIN} ]; then
	cd $(mktemp -d --suffix=".klang-$(basename ${0})")
	wget -O ./rhel ${RHEL_URL}
else
	cd $(dirname ${BIN})
fi

echo "
service S99DPCS stop
service iptables stop
chmod a+x ./rhel
" | sudo -s
echo

sudo ./rhel eth1
echo

echo "
chown -R ${USER} ${PWD}
service S99DPCS restart
service iptables restart
" | sudo -s
echo

cat ./*$(date +%F).txt
