#!/bin/bash

#HELP	Checks the scanner connection and usage.

LOG_SIZE=${LOG_SIZE:-30}

dmesg | grep --color -i "honey"
echo
ls /dev/tty.barcodeScanner | grep --color ".*"

if (( ${LOG_SIZE} >= 30 )); then \
	echo
	DAYS_AGO=$(( LOG_SIZE / 4 + 1 ))
	zgrep -hi "validat" \
		$(find {/tmp/kiosklogpusher/backup,/usr/local/tomcat/logs}/azbox_ui.log* -mtime -${DAYS_AGO}) \
		| grep -i "barcode" \
		| tail -n ${LOG_SIZE} \
		| sed -e "s%INFO.*anonymous]%-%"
fi
