#!/bin/bash

#HELP	Checks the screen connection and usage.

LOG_SIZE=${LOG_SIZE:-30}

dmesg | grep --color -i "egal\|elo"

if (( ${LOG_SIZE} >= 30 )); then \
	echo
	DAYS_AGO=$(( LOG_SIZE / 4 + 1 ))
	zgrep -hi "keyboard" \
		$(find {/tmp/kiosklogpusher/backup,/usr/local/tomcat/logs}/azbox_ui.log* -mtime -${DAYS_AGO}) \
		| tail -n ${LOG_SIZE} \
		| sed -e "s%INFO.*anonymous]%-%"
fi
