#!/bin/bash

#HELP	[slotnr] - open a slot [slotnr]\nslot-open [nr1] [nr2] [nr3] - opens multiple slots\nslot-open all - opens all slots.

MSG="a single slot"
TARGET="-d ${@}"

case ${#} in

	0)
		exit 1
		;;

	1)
		if [[ ${1} == "all" ]]; then
			MSG="ALL slots"
			TARGET=""
		fi
		;;

	*)
		MSG="multiple slots"
		;;

esac

cd /usr/local/dpcs

echo "# Opening ${MSG}:" | grep --color ".*"
sudo ./lockerController.sh -o ${TARGET}

exit ${?}
